default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: 'dev'
  password: 'dev'
  host: 'localhost'
  port: 5432

development:
  <<: *default
  database: Todo_development

test:
  <<: *default
  database: Todo_test

